version: "3.8"

services:
  backend:
    image: sanjanats3/vizai-backend:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - LLM_URI=http://llm:8000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - db

  llm:
    image: sanjanats3/vizai-llm:latest
    environment:
      - LLM_MODEL=gemini-1.5-flash

  frontend:
    image: sanjanats3/vizai-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

