version: "3.8"

services:
  backend:
    image: sanjanats3/vizai-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  llm:
    image: sanjanats3/vizai-llm:latest
    ports:
      - "8001:8000"
    env_file:
      - .env

  frontend:
    image: sanjanats3/vizai-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

